
server:
 port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.hz.springboot_mybatisplus.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false


